### PR TITLE
feat(demo): add more demos

### PR DESCRIPTION
**Pull request by meeroslav**
- [X]  Recursive demo
- [x] Restrictions demo
- [x] Responsive demo

### CODE REVIEW

**Comment by brandonroberts** [comment]
I don't think we need separate demos for each of these. What do you think about rolling them into one demo app?

**Comment by meeroslav** [comment]
Each one of them is targeting a different feature. It makes it easier for devs to find an example of how to do a specific thing. This could be a base for documentation. Additionally, including E2E tests into CI brings extra checks.

Merging them all together would create a multi-concern app that would be harder to read.

I would, though, remove the `getting-started` and `tour-of-heroes` and replace them with demo apps showing the `@angular/router` working alongside `angular-routing` and "auxiliary routes" (multiple routers on the same component).

What do you think about this proposal?

**Comment by brandonroberts** [comment]
That sounds reasonable to me

**Comment by meeroslav** [comment]
Please merge this one in then and I'll create additional PR for new demos and removal of the two above mentioned

**Pull request merged**
